# docker-compose.yml
version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: samcart
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: samcart
    container_name: postgres
    volumes:
    - "./db/pg:/var/lib/postgresql/data"
  db-migrator:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db-migrator
    depends_on: 
      - postgres
    environment: 
      DB_HOST: host.docker.internal
  cars:
    build:
      context: ./cars
      dockerfile: Dockerfile
    container_name: cars
    restart: always
    volumes:
      - ./cars/:/app
      - /app/node_modules
    depends_on:
      - postgres
      - db-migrator
    environment:
      DB_HOST: host.docker.internal
      POSTGRES_USER: samcart
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: samcart
    ports:
      - "3000:3000"
  car:
    build:
      context: ./car
      dockerfile: Dockerfile
    container_name: car
    restart: always
    depends_on:
      - postgres
      - db-migrator
    volumes:
      - ./car/:/app/
      - /app/node_modules
    environment:
      DB_HOST: host.docker.internal
      POSTGRES_USER: samcart
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: samcart
    ports:
      - "3001:3001"